-- SQL schema

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `firebase_uid` VARCHAR(255) NOT NULL UNIQUE,
  `api_key` VARCHAR(255) UNIQUE,
  `alpaca_secret` VARCHAR(255) DEFAULT NULL,
  `wallet` DECIMAL(18,8) NOT NULL DEFAULT 0,
  `role` ENUM('USER','ADMIN') NOT NULL DEFAULT 'USER',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `sessions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT NOT NULL,
  `start_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `stop_timestamp` DATETIME DEFAULT NULL,
  `pnl` DECIMAL(18,8) DEFAULT NULL,
  `status` ENUM('ACTIVE','STOPPED','COMPLETED','FAILED') NOT NULL DEFAULT 'ACTIVE',
  INDEX `idx_sessions_user_id` (`user_id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `trades` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `session_id` INT NOT NULL,
  `price` DECIMAL(18,8) NOT NULL,
  `quantity` DECIMAL(18,8) NOT NULL,
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `type` ENUM('BUY','SELL') NOT NULL,
  INDEX `idx_trades_session_id` (`session_id`),
  FOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON DELETE CASCADE
);
