-- SQL schema

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `firebase_token` VARCHAR(255) UNIQUE,
  `api_key` VARCHAR(255) UNIQUE,
  `wallet` DECIMAL(18,8) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `sessions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT NOT NULL,
  `start_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `stop_timestamp` DATETIME DEFAULT NULL,
  `pnl` DECIMAL(18,8) DEFAULT NULL,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `actions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `session_id` INT NOT NULL,
  `sum` DECIMAL(18,8) NOT NULL,
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `type` ENUM('BUY','SELL') NOT NULL,
  FOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON DELETE CASCADE
);
